# Generated by Django 4.1.1 on 2024-02-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='individualdetails',
            table=None,
        ),
    ]
